project:
  type: book
  output-dir: _book

book:
  title: "Coding for Economists"
  author: "Arthur Turrell"
  favicon: favicon.ico
  cover-image: smith_lovelace.png
  site-url: https://aeturrell.github.io/coding-for-economists
  repo-url: https://github.com/aeturrell/coding-for-economists
  repo-branch: main
  repo-actions: [edit, issue]
  google-analytics: "G-9FZQCPFXZJ"
  page-footer: "This book is available under an MIT license."
  search: true
  chapters:
    - intro.qmd
    - part: "Getting Started"
      chapters:
        - code-preliminaries.qmd
        - code-basics.ipynb
        - workflow-basics.ipynb
        - code-where.ipynb
    - part: "Essential Data"
      chapters:
        - data-analysis-quickstart.ipynb
        - data-intro.ipynb
        - data-transformation.ipynb
        - data-read-and-write.qmd
        - data-numbers.ipynb
        - data-categorical.ipynb
        - data-spreadsheets.ipynb
    - part: "Essential Coding"
      chapters:
        - code-best-practice.qmd
        - code-advanced.ipynb
        - code-advcd-best-practice.ipynb
    - part: "Essential Data Visualisation"
      chapters:
        - vis-intro.ipynb
        - vis-letsplot.ipynb
        - vis-matplotlib.ipynb
        - vis-common-plots-one.ipynb
        - vis-common-plots-two.ipynb
    - part: "Essential Workflow"
      chapters:
        - auto-research-outputs.qmd
        - wrkflow-markdown.qmd
        - wrkflow-command-line.qmd
        - wrkflow-version-control.qmd
    - part: "Econometrics"
      chapters:
        - econmt-probability-random.ipynb
        - econmt-statistics.ipynb
        - econmt-regression.ipynb
        - econmt-generalised-models.ipynb
        - econmt-diagnostics.ipynb
        - econmt-causal-inference.qmd
        - econmt-bayesian.ipynb
        - econmt-bayes-bambi.ipynb
    - part: "Data"
      chapters:
        - data-boolean.ipynb
        - data-joining-data.ipynb
        - data-missing-values.ipynb
        - data-exploratory-analysis.ipynb
        - data-extraction.ipynb
        - data-databases.ipynb
        - data-advanced.ipynb
        - data-sharing.qmd
    - part: "Coding"
      chapters:
        - code-further-advanced.ipynb
    - part: "Data Visualisation"
      chapters:
        - vis-narrative.ipynb
        - vis-tables.ipynb
        - vis-dashboards.qmd
        - vis-animation.ipynb
    - part: "Workflow"
      chapters:
        - wrkflow-quarto.qmd
        - wrkflow-environments.qmd
        - wrkflow-rap.ipynb
    - part: "Time"
      chapters:
        - time-intro.ipynb
        - time-series.ipynb
        - time-fcasts-env.ipynb
    - part: "Text Analysis"
      chapters:
        - text-intro.ipynb
        - text-regex.ipynb
        - text-nlp.ipynb
    - part: "Machine Learning"
      chapters:
        - ml-intro.ipynb
        - ml-sup.ipynb
        - ml-data.ipynb
        - ml-unsup.ipynb
    - part: "Geospatial"
      chapters:
        - geo-intro.ipynb
        - geo-vis.ipynb
    - part: "Mathematics"
      chapters:
        - maths-abstract.ipynb
        - maths-numerical.ipynb
    - part: "Craft"
      chapters:
        - craft-intro.qmd
        - craft-search.qmd
        - craft-generating-ideas.qmd
        - craft-writing-papers.qmd
        - craft-research-blogs.qmd
        - craft-referee.qmd
        - craft-technical-reports.qmd
        - craft-extended-abstracts.qmd
    - part: "Further Data Visualisation"
      chapters:
        - vis-plotnine.ipynb
        - vis-seaborn.ipynb
    - part: "Coming from ..."
      chapters:
        - coming-from-stata.qmd
        - coming-from-matlab.qmd
        - coming-from-r.qmd
        - coming-from-excel.qmd
    - part: "End Matter"
      chapters:
        - contributing.qmd
        - zreferences.qmd

bibliography: references.bib
csl: csl/chicago-author-date.csl

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 3
    html-math-method: katex
    code-copy: true
    code-link: true
    code-overflow: wrap
    number-sections: false
    include-in-header:
      - text: |
          <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"></script>

execute:
  freeze: auto
  error: false
