name: release

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.5.57"

      - name: set timezone
        run: |
          TZ="Europe/London" &&
          sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

      - name: install linux deps
        run: |
          sudo apt-get -y install openssl graphviz nano texlive graphviz-dev unzip

      - name: install special fonts
        run: |
          mkdir -p /usr/share/fonts/truetype/ &&
          wget https://www.wfonts.com/download/data/2015/10/08/varta/varta.zip &&
          unzip varta.zip &&
          install -m644 *.ttf /usr/share/fonts/truetype/ &&
          rm *.ttf
          rm varta.zip

      - name: install text models
        run: |
          uv run python3 -m spacy download en_core_web_sm &&
          uv run python3 -m nltk.downloader all

      - name: git config  # Needed as git config --get user.name is used in one example
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)" &&
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: build the book
        run: |
          uv run quarto render

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "::set-output name=sha::$(git rev-parse --verify --quiet HEAD^)"

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v2.0.3
        with:
          version-command: |
            python3 -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])"

      - name: Bump version for developmental release
        if: "! steps.check-version.outputs.tag"
        run: |
          uv run python version_bumper.py &&
          version=$(uv run toml get --toml-path=pyproject.toml project.version) &&
          uv run toml set --toml-path=pyproject.toml project.version $version.dev.$(date +%s)

      - name: Publish
        if: steps.check-version.outputs.tag
        run: uv run ghp-import -n -p -f _book

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v6.0.0
        with:
          publish: ${{ steps.check-version.outputs.tag != '' }}
          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Success
        if: steps.check-version.outputs.tag
        run: |
          echo "Success in releasing a new version of Coding for Economists!"
