name: tests

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.5.57"

      - name: set timezone
        run: |
          TZ="Europe/London" &&
          sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

      - name: install linux deps
        run: |
          sudo apt-get -y install openssl graphviz nano texlive graphviz-dev unzip

      - name: install special fonts
        run: |
          mkdir -p /usr/share/fonts/truetype/ &&
          wget https://www.wfonts.com/download/data/2015/10/08/varta/varta.zip &&
          unzip varta.zip &&
          install -m644 *.ttf /usr/share/fonts/truetype/ &&
          rm *.ttf
          rm varta.zip

      - name: install text models
        run: |
          uv run python3 -m spacy download en_core_web_sm &&
          uv run python3 -m nltk.downloader all

      - name: git config  # Needed as git config --get user.name is used in one example
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)" &&
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: build the book
        run: |
          uv run quarto render --execute
        env:
            # This forces Quarto to use the Python inside your uv venv
            QUARTO_PYTHON: .venv/bin/python

      - name: success
        run: |
          echo "Success in building book without errors!"
